#!/bin/bash

echo " "
echo "******************************************************************"
echo "       Informacion para la ejecucion de scripts y programas"
echo "******************************************************************"
echo " "
echo "Registro Continuo y Adquisicion (SPI):"
echo "  Iniciar pipeline:      registrocontinuo start"
echo "  Detener pipeline:      registrocontinuo stop"
echo "  Reiniciar pipeline:    registrocontinuo restart"
echo "  Estado del servicio:   sudo systemctl status rsa-acelerografo.service"
echo "  Ver tramas en vivo:    comprobar"
echo "  Resetear dsPIC (HW):   sudo resetmaster"
echo " "
echo "Google Drive y Sincronizacion MiniSEED:"
echo "  Subida manual a Drive: \$PROJECT_LOCAL_ROOT/.venv/bin/python3 \$PROJECT_LOCAL_ROOT/scripts/drive/gestor_archivos_acq.py"
echo "  Simular subida (test): \$PROJECT_LOCAL_ROOT/.venv/bin/python3 \$PROJECT_LOCAL_ROOT/scripts/drive/gestor_archivos_acq.py --dry-run"
echo "  Ver log de subidas:    tail -f \$PROJECT_LOCAL_ROOT/log-files/gestor_acq.log"
echo "  Ver registro subidas:  cat \$PROJECT_LOCAL_ROOT/log-files/uploaded_files_registry.json"
echo " "
echo "Supervisor (Servicios de fondo):"
echo "  Ver estado general:    sudo supervisorctl status"
echo "  Iniciar servicio:      sudo supervisorctl start <servicio>"
echo "  Detener servicio:      sudo supervisorctl stop <servicio>"
echo "  Reiniciar servicio:    sudo supervisorctl restart <servicio>"
echo "  Reiniciar todos:       sudo supervisorctl restart all"
echo "  Ver logs en vivo:      sudo supervisorctl tail -f <servicio>"
echo "  Recargar config:       sudo supervisorctl reread && sudo supervisorctl update"
echo "  Servicios principales: config_server, gpd_worker, mqtt_coordinator, stream_processor"
echo " "
echo "Punto de Acceso WiFi (AP):"
echo "  Instalar dependencias: sudo wifiap install"
echo "  Activar AP:            sudo wifiap enable"
echo "  Desactivar AP:         sudo wifiap disable"
echo "  Consultar estado:      sudo wifiap status"
echo " "
echo "Diagnostico Automatizado (Reporte para Agente IA):"
echo "  Diagnostico completo:  diagnostico"
echo "  Solo adquisicion:      diagnostico acquisition"
echo "  Solo sensor:           diagnostico sensor"
echo "  Solo Drive:            diagnostico drive"
echo "  Modo silencioso:       diagnostico --quiet"
echo "  Ver ultimo reporte:    cat \$PROJECT_LOCAL_ROOT/log-files/diagnostico_report.log"
echo " "
echo "Informacion del Sistema:"
echo "  Rutas y espacio disco: informacion"
echo " "
exit 0