#!/bin/bash

echo " "
echo "******************************************************************"
echo "       Informacion para la ejecucion de scripts y programas"
echo "******************************************************************"
echo " "
echo "Registro Continuo:"
echo "  Iniciar: registrocontinuo start"
echo "  Detener: registrocontinuo stop"
echo " "
echo "Extraer evento:"
echo "  /home/rsa/ejecutables/extraerevento <nombreArchivoBinario> <tiempoSegundos> <duracionSegundos>"
echo "  "
echo "Convertir mseed:"
echo "  python3 /home/rsa/ejecutables/conversor_mseed.py <1-2> "
echo "    <1>: Registro continuo"
echo "    <2>: Evento extraido"
echo "  "
echo "Punto de Acceso WiFi (AP):"
echo "  Instalar dependencias: sudo wifiap install"
echo "  Activar AP:            sudo wifiap enable"
echo "  Desactivar AP:         sudo wifiap disable"
echo "  Consultar estado:      sudo wifiap status"
echo " "
echo "Supervisor (Servicios de fondo):"
echo "  Ver estado general:    sudo supervisorctl status"
echo "  Reiniciar servicio:    sudo supervisorctl restart <servicio>"
echo "  Servicios principales: config_server, mqtt_coordinator"
echo " "
exit 0