[program:config_server]
command={{PROJECT_LOCAL_ROOT}}/.venv/bin/python3 {{PROJECT_LOCAL_ROOT}}/scripts/web/config_server.py
directory={{PROJECT_LOCAL_ROOT}}/scripts/web/
environment=PROJECT_LOCAL_ROOT="{{PROJECT_LOCAL_ROOT}}",PROJECT_GIT_ROOT="{{PROJECT_GIT_ROOT}}"
autostart=true
autorestart=true
startretries=3
user=rsa
stdout_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_config_server.log
stderr_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_config_server.err
