[program:gpd_worker]
command={{PROJECT_LOCAL_ROOT}}/.venv/bin/python3 {{PROJECT_LOCAL_ROOT}}/scripts/streaming/gpd_stream_worker.py
directory={{PROJECT_LOCAL_ROOT}}/scripts/streaming/
environment=PROJECT_LOCAL_ROOT="{{PROJECT_LOCAL_ROOT}}"
autostart=true
autorestart=true
startretries=3
startsecs=10
user=rsa
stdout_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_gpd_worker.log
stderr_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_gpd_worker.err
