[program:mqtt_coordinator]
command={{PROJECT_LOCAL_ROOT}}/.venv/bin/python3 {{PROJECT_LOCAL_ROOT}}/scripts/mqtt/mqtt_coordinator.py
directory={{PROJECT_LOCAL_ROOT}}/scripts/mqtt/
environment=PROJECT_LOCAL_ROOT="{{PROJECT_LOCAL_ROOT}}"
autostart=true
autorestart=true
startretries=3
user=rsa
stdout_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_mqtt.log
stderr_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_mqtt.err