[program:stream_processor]
command={{PROJECT_LOCAL_ROOT}}/.venv/bin/python3 {{PROJECT_LOCAL_ROOT}}/scripts/streaming/stream_processor.py
directory={{PROJECT_LOCAL_ROOT}}/scripts/streaming/
environment=PROJECT_LOCAL_ROOT="{{PROJECT_LOCAL_ROOT}}"
autostart=true
autorestart=true
startretries=3
user=rsa
stdout_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_stream_processor.log
stderr_logfile={{PROJECT_LOCAL_ROOT}}/log-files/supervisor_stream_processor.err
